---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kyuubi-nineinfra-tech-v1alpha1-kyuubicluster
  failurePolicy: Fail
  name: mkyuubicluster.kb.io
  rules:
  - apiGroups:
    - kyuubi.nineinfra.tech
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kyuubiclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kyuubi-nineinfra-tech-v1alpha1-kyuubicluster
  failurePolicy: Fail
  name: vkyuubicluster.kb.io
  rules:
  - apiGroups:
    - kyuubi.nineinfra.tech
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kyuubiclusters
  sideEffects: None
