/*
Copyright 2023 nineinfra.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/nineinfra/kyuubi-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKyuubiClusters implements KyuubiClusterInterface
type FakeKyuubiClusters struct {
	Fake *FakeKyuubiV1alpha1
	ns   string
}

var kyuubiclustersResource = v1alpha1.SchemeGroupVersion.WithResource("kyuubiclusters")

var kyuubiclustersKind = v1alpha1.SchemeGroupVersion.WithKind("KyuubiCluster")

// Get takes name of the kyuubiCluster, and returns the corresponding kyuubiCluster object, and an error if there is any.
func (c *FakeKyuubiClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KyuubiCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kyuubiclustersResource, c.ns, name), &v1alpha1.KyuubiCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KyuubiCluster), err
}

// List takes label and field selectors, and returns the list of KyuubiClusters that match those selectors.
func (c *FakeKyuubiClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KyuubiClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kyuubiclustersResource, kyuubiclustersKind, c.ns, opts), &v1alpha1.KyuubiClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KyuubiClusterList{ListMeta: obj.(*v1alpha1.KyuubiClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.KyuubiClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kyuubiClusters.
func (c *FakeKyuubiClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kyuubiclustersResource, c.ns, opts))

}

// Create takes the representation of a kyuubiCluster and creates it.  Returns the server's representation of the kyuubiCluster, and an error, if there is any.
func (c *FakeKyuubiClusters) Create(ctx context.Context, kyuubiCluster *v1alpha1.KyuubiCluster, opts v1.CreateOptions) (result *v1alpha1.KyuubiCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kyuubiclustersResource, c.ns, kyuubiCluster), &v1alpha1.KyuubiCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KyuubiCluster), err
}

// Update takes the representation of a kyuubiCluster and updates it. Returns the server's representation of the kyuubiCluster, and an error, if there is any.
func (c *FakeKyuubiClusters) Update(ctx context.Context, kyuubiCluster *v1alpha1.KyuubiCluster, opts v1.UpdateOptions) (result *v1alpha1.KyuubiCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kyuubiclustersResource, c.ns, kyuubiCluster), &v1alpha1.KyuubiCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KyuubiCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKyuubiClusters) UpdateStatus(ctx context.Context, kyuubiCluster *v1alpha1.KyuubiCluster, opts v1.UpdateOptions) (*v1alpha1.KyuubiCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kyuubiclustersResource, "status", c.ns, kyuubiCluster), &v1alpha1.KyuubiCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KyuubiCluster), err
}

// Delete takes name of the kyuubiCluster and deletes it. Returns an error if one occurs.
func (c *FakeKyuubiClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(kyuubiclustersResource, c.ns, name, opts), &v1alpha1.KyuubiCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKyuubiClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kyuubiclustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KyuubiClusterList{})
	return err
}

// Patch applies the patch and returns the patched kyuubiCluster.
func (c *FakeKyuubiClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KyuubiCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kyuubiclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.KyuubiCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KyuubiCluster), err
}
